apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-issuers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ostbytestorg/p-corp-engineers-iac.git
    targetRevision: FEAT/ARGOCDREPOCONNECT
    path: ARGOCD/infrastructure/issuers
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true