apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: netbox-postgres
  namespace: netbox
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: "12.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1h
  values:
    global:
      postgresql:
        auth:
          postgresPassword: "CHANGE_ME"
          username: netbox
          password: "CHANGE_ME"
          database: netbox
