apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./FLUX/infrastructure/nginx-ingress
  prune: true