apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: netbox
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/netbox-community/netbox-chart
  provider: generic