apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ostbytestorg/p-corp-engineers-iac.git'  # Replace with your repo URL
    targetRevision: HEAD
    path: ARGOCD/helloworld-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: helloworld
  syncPolicy:
    automated:
      prune: true
      selfHeal: true