# FLUX/apps/netbox/base/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 5m
  chart:
    spec:
      chart: netbox
      version: "3.6.0"
      sourceRef:
        kind: HelmRepository
        name: bootc
        namespace: flux-system
  values:
    image:
      repository: netboxcommunity/netbox
      tag: v4.2.6
    
    superuser:
      name: admin
      email: ostbym@proton.me
      password: "admin-password"  # Change this for production
    
    allowedHosts: "*"
    
    postgresql:
      enabled: false
      externalDatabase:
        host: postgresql.netbox.svc.cluster.local
        port: 5432
        database: netbox
        username: netbox
        password: "netbox-password"  # Match with PostgreSQL password
    
    redis:
      enabled: false
      externalRedis:
        host: redis-master.netbox.svc.cluster.local
        password: "redis-password"  # Match with Redis password
    
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: ""  # We'll use IP-based access initially
          paths:
            - path: /
              pathType: Prefix