# FLUX/apps/netbox/postgres/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: netbox
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "12.5.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: netbox
      password: "netbox-password"  # You should use a secret manager in production
      database: netbox
    primary:
      persistence:
        size: 2Gi