# FLUX/apps/netbox/redis/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: netbox
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: "17.11.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      password: "redis-password"  # You should use a secret manager in production
    master:
      persistence:
        size: 2Gi