apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 15m
  chart:
    spec:
      chart: netbox
      sourceRef:
        kind: HelmRepository
        name: netbox
        namespace: flux-system
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: netbox-config
    - kind: Secret
      name: netbox-secret
