# FLUX/clusters/aksostbyengineeering001/apps/netbox.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: netbox
  namespace: flux-system
spec:
  interval: 10m
  path: ./FLUX/apps/netbox
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m