name: Configure AKS Cluster with Flux

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  configure-kube:
    runs-on:
      group: vnet-spoke-production-engineers
    environment: Production-plan
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login (Federated credentials)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.CLIENTID }}
          tenant-id: ${{ vars.TENANTID }}
          allow-no-subscriptions: true

      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          cluster-name: aksostbyengineeering001
          resource-group: rg-tf-aks

      - name: Install kubelogin
        run: |
          echo "Downloading kubelogin..."
          curl -L -o kubelogin.zip https://github.com/Azure/kubelogin/releases/download/v0.2.7/kubelogin-linux-amd64.zip
          unzip kubelogin.zip
          chmod +x bin/linux_amd64/kubelogin
          sudo mv bin/linux_amd64/kubelogin /usr/local/bin/kubelogin
          kubelogin --version

      - name: Convert kubeconfig for noninteractive login using azurecli mode
        run: |
          echo "Converting kubeconfig to noninteractive azurecli mode..."
          kubelogin convert-kubeconfig --login azurecli

      - name: Install Flux CLI
        run: |
          echo "Installing Flux CLI..."
          curl -s https://fluxcd.io/install.sh | sudo bash
          flux --version

      - name: Setup SSH key for Flux
        env:
          SSH_PRIVATE_KEY: ${{ secrets.FLUX_SSH_PRIVATE_KEY }}
        run: |
          # Set up the SSH key for Flux
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/flux-deploy-key
          chmod 600 ~/.ssh/flux-deploy-key
          
          # Configure SSH to use this key for github.com
          cat > ~/.ssh/config << EOF
          Host github.com
            IdentityFile ~/.ssh/flux-deploy-key
            StrictHostKeyChecking no
          EOF
          
          chmod 600 ~/.ssh/config
          
          # Add github.com to known hosts to avoid prompts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Bootstrap Flux
        run: |
          # Bootstrap Flux using the configured SSH setup
            flux bootstrap git \
              --url=ssh://git@github.com:ostbytestorg/p-corp-engineers-iac.git \
              --branch=FEAT/FLUX-1 \
              --private-key-file=~/.ssh/flux-deploy-key \
              --password="" \
              --path=FLUX
          
          echo "Flux bootstrap completed successfully!"
          
          # Verify Flux installation
          kubectl get pods -n flux-system
          flux get all