name: Deploy RG via Terraform

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: 
        - "TF/DNS/**"
  push:
    branches: [ main ]
    paths: 
        - "TF/DNS/**"

  workflow_dispatch:

jobs:
  azure-login:
    runs-on:
      group: vnet-spoke-production-engineers
    environment: Production-plan
    steps:
    - name: Azure Login (Federated credentials)
      uses: azure/login@v2
      with:
          client-id: ${{ vars.CLIENTID }} # LZ SP clientId
          tenant-id: ${{ vars.TENANTID }} # your Azure AD tenant
          enable-AzPSSession: true
          allow-no-subscriptions: true

  terraform:
    needs: azure-login
    uses: ostbytestorg/tf-buildtemplate/.github/workflows/tf-plan-apply.yml@main
    with:
      tfDirectory: "./TF/DNS"   # Folder containing our Terraform config
      jobEnvironment: "Production-plan"
      tfStateKey: "dns.tfstate"