name: Deploy FunctionApp via TF

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: 
        - "TF/FunctionApp/**"
  push:
    branches: [ main ]
    paths: 
        - "TF/FunctionApp/**"

  workflow_dispatch:

jobs:
  azure-login:
    runs-on:
      group: vnet-spoke-production-engineers
    environment: Production-plan
    steps:
    - name: Azure Login (Federated credentials)
      uses: azure/login@v2
      with:
          client-id: ${{ vars.CLIENTID }} # LZ SP clientId
          tenant-id: ${{ vars.TENANTID }} # your Azure AD tenant
          enable-AzPSSession: true
          allow-no-subscriptions: true

  terraform:
    needs: azure-login
    uses: ostbytestorg/tf-buildtemplate/.github/workflows/tf-plan-apply.yml@main
    with:
      tfDirectory: "./TF/FunctionApp"   # Folder containing our Terraform config
      jobEnvironment: "Production-plan"
      tfStateKey: "function.tfstate"

  deploy-functions:
    needs: terraform
    runs-on: ubuntu-latest
    environment: Production-plan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login for Function Deployment
        uses: azure/login@v2
        with:
          client-id: ${{ vars.CLIENTID }}
          tenant-id: ${{ vars.TENANTID }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      - name: Deploy PowerShell Function App Code
        uses: Azure/functions-action@v1
        with:
          app-name: "my-function-app-name"   # Explicit function app name reference
          package: './FunctionApp'  